<?php

// Global Extensions //

wfLoadExtensions( [
	'AbuseFilter',
	'AdvancedMeta',
	'AdvancedSearch',
	'BetaFeatures',
	'CategoryTree',
	'CentralAuth',
	'CentralNotice', 
	'CheckUser',
	'CodeEditor',
	'CodeMirror',
	'InputBox', 
	'ImageMap', 
	'Interwiki', 
	'CharInsert', 
	'CirrusSearch',
	'Cite',
	'CiteThisPage', 
	'ConfirmEdit', 
	'Echo', 
	'EditUser', 
	'Elastica', 
	'FlaggedRevs', 
	'Flow', 
	'GlobalBlocking', 
	'GlobalCssJs', 
	'GlobalPreferences', 
	'GlobalUserPage', 
	'Gadgets',
	'LocalisationUpdate', 
	'MassMessage', 
	'MultimediaViewer',
	'Nuke',
	'Poem',
	'ProtectSite', 
	'ParserFunctions', 
	'ReplaceText',
	'Translate', 
	'UniversalLanguageSelector',
	'UserMerge', 
	'VisualEditor',
	'WikiEditor',
] );
