<?php
wfLoadExtensions( [	
    'AbuseFilter',
	'AdvancedMeta',
	'AdvancedSearch',
//	'AntiSpoof',
	'Babel',
	'BetaFeatures',
	'BounceHandler',
	'ContactPage',
        'Interwiki',
	'Capiunto',
	'CentralAuth',
	'CentralNotice',
        'Flow',
	'CirrusSearch',
	'CharInsert',
	'CheckUser',
	'CiteThisPage',
	'CodeReview',
	'CodeMirror',
//	'ConfirmAccount', //db
//      'CheckUser',
	'ConfirmEdit',
	'Cite',
	'ContentTranslation',
	'CodeEditor',
	'DismissableSiteNotice',
//	'Disambiguator',
    	'DiscussionTools',
	'Linter',
	'Echo',
	'EditUser',
	'EntitySchema',
	'Gadgets',
	'Elastica',
	'EventLogging',
	'EventStreamConfig',
	'GlobalBlocking',
	'GlobalCssJs',
	'GlobalPreferences',
	'GlobalUsage',
	'GlobalUserPage',
	'GuidedTour',
	'Graph',
	'HoverGallery',
	'InputBox',
//      'JsonConfig',
//	'Kartographer',
	'MassMessage',
	'MobileFrontend',
	'MultimediaViewer',
	'NewUserMessage',
	'Nuke',
	'Newsletter',
	'NewsTicker',
	'OATHAuth',
	'OAuth',
//	'PageViewInfo',
//	'PageTriage',
//	'PagedTiffHandler',
	'PageImages',
	'ParserFunctions',
	'PdfHandler',
	'RelatedArticles',
	'Renameuser',
	'ReplaceText',
	'SiteMatrix',
	'SecurePoll',
	'SecureLinkFixer',
	'SpamBlacklist',
	'Scribunto',
	'SyntaxHighlight_GeSHi',
        'Linter',
	'TemplateData',
	'TemplateStyles',
	'TemplateSandbox',
	'TemplateWizard',
	'TextExtracts',
	'Thanks',
	'TitleBlacklist',
	'TimedMediaHandler',
	'TorBlock',
	'Translate',
	'TranslationNotifications',
	'TwoColConflict',
	'UniversalLanguageSelector',
	'UploadsLink',
	'UploadWizard',
	'UserMerge',
	'VipsScaler',
	'VisualEditor',
	'WikiEditor',
	'WikimediaBadges',
	'WikimediaMessages',
//	'WikibaseLexeme',
	'WikiLove',
] );
$wgScribuntoDefaultEngine = 'luastandalone';
$wgScribuntoUseGeSHi = true;
$wgScribuntoUseCodeEditor = true;
